// Database types matching the actual schema
export interface Database {
  public: {
    Tables: {
      events: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          short_description: string | null;
          start_time: string;
          end_time: string;
          timezone: string;
          all_day: boolean;
          venue_id: string | null;
          custom_location: string | null;
          organizer_id: string | null;
          category_id: string | null;
          poster_url: string | null;
          gallery_urls: string[];
          tags: string[];
          is_free: boolean;
          price_range: number[];
          ticket_url: string | null;
          registration_required: boolean;
          capacity: number | null;
          ai_score_factors: Json;
          popularity_score: number;
          quality_score: number;
          status: string;
          is_featured: boolean;
          is_trending: boolean;
          source_url: string | null;
          source_type: string | null;
          last_scraped_at: string | null;
          scrape_hash: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          short_description?: string | null;
          start_time: string;
          end_time: string;
          timezone?: string;
          all_day?: boolean;
          venue_id?: string | null;
          custom_location?: string | null;
          organizer_id?: string | null;
          category_id?: string | null;
          poster_url?: string | null;
          gallery_urls?: string[];
          tags?: string[];
          is_free?: boolean;
          price_range?: number[];
          ticket_url?: string | null;
          registration_required?: boolean;
          capacity?: number | null;
          ai_score_factors?: Json;
          popularity_score?: number;
          quality_score?: number;
          status?: string;
          is_featured?: boolean;
          is_trending?: boolean;
          source_url?: string | null;
          source_type?: string | null;
          last_scraped_at?: string | null;
          scrape_hash?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          short_description?: string | null;
          start_time?: string;
          end_time?: string;
          timezone?: string;
          all_day?: boolean;
          venue_id?: string | null;
          custom_location?: string | null;
          organizer_id?: string | null;
          category_id?: string | null;
          poster_url?: string | null;
          gallery_urls?: string[];
          tags?: string[];
          is_free?: boolean;
          price_range?: number[];
          ticket_url?: string | null;
          registration_required?: boolean;
          capacity?: number | null;
          ai_score_factors?: Json;
          popularity_score?: number;
          quality_score?: number;
          status?: string;
          is_featured?: boolean;
          is_trending?: boolean;
          source_url?: string | null;
          source_type?: string | null;
          last_scraped_at?: string | null;
          scrape_hash?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
      event_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          color: string;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          icon?: string | null;
          color?: string;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          color?: string;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
      };
      venues: {
        Row: {
          id: string;
          name: string;
          slug: string;
          address: string;
          city: string;
          latitude: number | null;
          longitude: number | null;
          website_url: string | null;
          contact_info: Json;
          capacity: number | null;
          venue_type: string | null;
          amenities: string[];
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          address: string;
          city?: string;
          latitude?: number | null;
          longitude?: number | null;
          website_url?: string | null;
          contact_info?: Json;
          capacity?: number | null;
          venue_type?: string | null;
          amenities?: string[];
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          address?: string;
          city?: string;
          latitude?: number | null;
          longitude?: number | null;
          website_url?: string | null;
          contact_info?: Json;
          capacity?: number | null;
          venue_type?: string | null;
          amenities?: string[];
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      organizers: {
        Row: {
          id: string;
          user_id: string | null;
          organization_name: string;
          contact_email: string;
          contact_phone: string | null;
          website_url: string | null;
          social_links: Json;
          bio: string | null;
          logo_url: string | null;
          is_verified: boolean;
          verification_level: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          organization_name: string;
          contact_email: string;
          contact_phone?: string | null;
          website_url?: string | null;
          social_links?: Json;
          bio?: string | null;
          logo_url?: string | null;
          is_verified?: boolean;
          verification_level?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          organization_name?: string;
          contact_email?: string;
          contact_phone?: string | null;
          website_url?: string | null;
          social_links?: Json;
          bio?: string | null;
          logo_url?: string | null;
          is_verified?: boolean;
          verification_level?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          created_at: string;
          updated_at: string;
          city: string;
          preferred_radius: number;
          preferred_categories: string[];
          preferred_times: string[];
          preferred_price_range: number[];
          ai_preferences: Json;
          is_pro: boolean;
          pro_expires_at: string | null;
          stripe_customer_id: string | null;
          notification_preferences: Json;
          is_public: boolean;
          email_verified: boolean;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
          city?: string;
          preferred_radius?: number;
          preferred_categories?: string[];
          preferred_times?: string[];
          preferred_price_range?: number[];
          ai_preferences?: Json;
          is_pro?: boolean;
          pro_expires_at?: string | null;
          stripe_customer_id?: string | null;
          notification_preferences?: Json;
          is_public?: boolean;
          email_verified?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
          city?: string;
          preferred_radius?: number;
          preferred_categories?: string[];
          preferred_times?: string[];
          preferred_price_range?: number[];
          ai_preferences?: Json;
          is_pro?: boolean;
          pro_expires_at?: string | null;
          stripe_customer_id?: string | null;
          notification_preferences?: Json;
          is_public?: boolean;
          email_verified?: boolean;
        };
      };
      user_events: {
        Row: {
          id: string;
          user_id: string;
          event_id: string;
          save_type: string;
          calendar_reminder: boolean;
          reminder_minutes: number;
          personal_notes: string | null;
          is_public: boolean;
          invited_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_id: string;
          save_type?: string;
          calendar_reminder?: boolean;
          reminder_minutes?: number;
          personal_notes?: string | null;
          is_public?: boolean;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_id?: string;
          save_type?: string;
          calendar_reminder?: boolean;
          reminder_minutes?: number;
          personal_notes?: string | null;
          is_public?: boolean;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_subscription_id: string;
          status: string;
          plan_type: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          amount: number;
          currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_subscription_id: string;
          status: string;
          plan_type?: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          amount: number;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_subscription_id?: string;
          status?: string;
          plan_type?: string;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          amount?: number;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          subscription_id: string | null;
          stripe_payment_intent_id: string;
          amount: number;
          currency: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subscription_id?: string | null;
          stripe_payment_intent_id: string;
          amount: number;
          currency?: string;
          status: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subscription_id?: string | null;
          stripe_payment_intent_id?: string;
          amount?: number;
          currency?: string;
          status?: string;
          created_at?: string;
        };
      };
      user_usage: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          swipes_count: number;
          superlikes_count: number;
          searches_count: number;
          advanced_filters_used: number;
          early_alerts_sent: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date?: string;
          swipes_count?: number;
          superlikes_count?: number;
          searches_count?: number;
          advanced_filters_used?: number;
          early_alerts_sent?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          swipes_count?: number;
          superlikes_count?: number;
          searches_count?: number;
          advanced_filters_used?: number;
          early_alerts_sent?: number;
          created_at?: string;
        };
      };
      user_calendar_events: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          start_time: string;
          end_time: string;
          timezone: string;
          all_day: boolean;
          location: string | null;
          virtual_meeting_url: string | null;
          recurrence_pattern: Json | null;
          parent_event_id: string | null;
          original_start_time: string | null;
          status: string;
          priority: string;
          visibility: string;
          color: string | null;
          created_by: string;
          external_calendar_id: string | null;
          external_event_id: string | null;
          sync_status: string | null;
          created_at: string;
          updated_at: string;
          last_sync_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          start_time: string;
          end_time: string;
          timezone?: string;
          all_day?: boolean;
          location?: string | null;
          virtual_meeting_url?: string | null;
          recurrence_pattern?: Json | null;
          parent_event_id?: string | null;
          original_start_time?: string | null;
          status?: string;
          priority?: string;
          visibility?: string;
          color?: string | null;
          created_by: string;
          external_calendar_id?: string | null;
          external_event_id?: string | null;
          sync_status?: string | null;
          created_at?: string;
          updated_at?: string;
          last_sync_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          start_time?: string;
          end_time?: string;
          timezone?: string;
          all_day?: boolean;
          location?: string | null;
          virtual_meeting_url?: string | null;
          recurrence_pattern?: Json | null;
          parent_event_id?: string | null;
          original_start_time?: string | null;
          status?: string;
          priority?: string;
          visibility?: string;
          color?: string | null;
          created_by?: string;
          external_calendar_id?: string | null;
          external_event_id?: string | null;
          sync_status?: string | null;
          created_at?: string;
          updated_at?: string;
          last_sync_at?: string | null;
        };
      };
      calendar_invitations: {
        Row: {
          id: string;
          event_id: string;
          inviter_id: string;
          inviter_name: string;
          invitee_email: string;
          invitee_name: string | null;
          invitee_user_id: string | null;
          status: string;
          rsvp_status: string;
          message: string | null;
          sent_at: string;
          response_at: string | null;
          expires_at: string | null;
          reminders_sent: number;
          last_reminder_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          inviter_id: string;
          inviter_name: string;
          invitee_email: string;
          invitee_name?: string | null;
          invitee_user_id?: string | null;
          status?: string;
          rsvp_status?: string;
          message?: string | null;
          sent_at?: string;
          response_at?: string | null;
          expires_at?: string | null;
          reminders_sent?: number;
          last_reminder_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          inviter_id?: string;
          inviter_name?: string;
          invitee_email?: string;
          invitee_name?: string | null;
          invitee_user_id?: string | null;
          status?: string;
          rsvp_status?: string;
          message?: string | null;
          sent_at?: string;
          response_at?: string | null;
          expires_at?: string | null;
          reminders_sent?: number;
          last_reminder_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      external_calendar_sync: {
        Row: {
          id: string;
          user_id: string;
          provider: string;
          provider_calendar_id: string;
          calendar_name: string;
          sync_direction: string;
          sync_status: string;
          access_token: string | null;
          refresh_token: string | null;
          last_sync_at: string | null;
          next_sync_at: string | null;
          sync_interval: number;
          error_count: number;
          last_error: string | null;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: string;
          provider_calendar_id: string;
          calendar_name: string;
          sync_direction?: string;
          sync_status?: string;
          access_token?: string | null;
          refresh_token?: string | null;
          last_sync_at?: string | null;
          next_sync_at?: string | null;
          sync_interval?: number;
          error_count?: number;
          last_error?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: string;
          provider_calendar_id?: string;
          calendar_name?: string;
          sync_direction?: string;
          sync_status?: string;
          access_token?: string | null;
          refresh_token?: string | null;
          last_sync_at?: string | null;
          next_sync_at?: string | null;
          sync_interval?: number;
          error_count?: number;
          last_error?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      calendar_conflicts: {
        Row: {
          id: string;
          user_id: string;
          event_id: string;
          conflicting_event_id: string;
          conflict_type: string;
          severity: string;
          overlap_minutes: number;
          resolution_suggestions: Json;
          is_resolved: boolean;
          resolved_at: string | null;
          resolution_method: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_id: string;
          conflicting_event_id: string;
          conflict_type: string;
          severity?: string;
          overlap_minutes: number;
          resolution_suggestions?: Json;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolution_method?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_id?: string;
          conflicting_event_id?: string;
          conflict_type?: string;
          severity?: string;
          overlap_minutes?: number;
          resolution_suggestions?: Json;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolution_method?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
